---
### Repo | Setup Docker repository
- name: Packages | Install dependencies packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
- name: Repo | Add GPG signing key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0755"
    force: true
- name: Repo | Add AMD64 repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present
  when: ansible_facts.architecture == "x86_64"
- name: Repo | Add armhf repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present
  when:
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"
- name: Repo | Add ARM64 repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present
  when:
    - ansible_facts.architecture is search("arm") and ansible_facts.userspace_bits == "64" or ansible_facts.architecture is search("aarch64")

### Docker | Install Docker packages
- name: Docker | Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apparmor-utils
    - containerd.io
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin

### Docker | Add user to docker group
- name: User | Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker

### Docker | Prune dangling images
- name: Docker | Clean Up
  block:
    - name: Docker | Prune dangling image
      community.docker.docker_prune:
        containers: false
        images: true
        images_filters:
          dangling: false
        networks: false
        volumes: false
        builder_cache: false
  rescue:
    - name: Docker | Docker API not found
      ansible.builtin.debug:
        msg: Docker API not found, maybe it is not installed

### Docker | Restart Docker service
- name: Docker | Create stacks directory exists
  ansible.builtin.file:
    path: /opt/stacks/
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
