---
name: CI - Main

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: irishlab-io/.github/.github/workflows/reusable-secret.yml@main

    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  ansible-lint:
    name: Call Ansible-Lint
    uses: irishlab-io/.github/.github/workflows/reusable-ansible-lint.yml@main

    needs:
      - secret

    with:
      configuration_file: "-c ./.config/.ansible-lint.yml"
      requirements_file: "./collections/requirements.yml"
